import ReactLenis from "lenis/react";
import type { Metadata } from "next";
import { DM_Serif_Text, Plus_Jakarta_Sans } from "next/font/google";
import { Suspense } from "react";
import '@splidejs/react-splide/css';
import './global.scss';
import Header from "./_components/general/Header/Header";
import LenisRecovery from "./_components/general/LenisRecovery/LenisRecovery";
import LenisRouteSync from "./_components/general/LenisRouteSync/LenisRouteSync";
import PageUnder from "./_components/general/PageUnder/PageUnder";
import PopupBlock from "./_components/general/PopupBlock/PopupBlock";
import Preloader from "./_components/general/Preloader/Preloader";
import LocaleProvider from "./_i18n/LocaleProvider";
import { getRequestLocale } from "./_i18n/server";
import {
  buildWorkCategories,
  getServicesCatalog,
  getWorksCatalog,
  mapWorkToCard,
} from "./_lib/catalog";

const dmSans = DM_Serif_Text({
  variable: "--font-title",
  weight: '400',
  subsets: ['latin', 'latin-ext'],
});

const plusSans = Plus_Jakarta_Sans({
  variable: "--font-main",
  subsets: ['latin', 'latin-ext', 'cyrillic-ext'],
});

export const metadata: Metadata = {
  title: "HarbStone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getRequestLocale();
  const [services, works] = await Promise.all([
    getServicesCatalog(locale),
    getWorksCatalog(locale),
  ]);
  const footerCategories = buildWorkCategories(
    services,
    works.map(mapWorkToCard)
  ).map((category) => ({
    label: category.label,
    children: category.children.map((child) => ({
      label: child.label,
      href: child.href,
    })),
  }));

  return (
    <html
      lang={locale}
      className={`${dmSans.variable} ${plusSans.className} h-full antialiased`}
    >
      <body className="min-h-full is-preloading">
        <ReactLenis root />
        <LenisRecovery />
        <Suspense fallback={null}>
          <LenisRouteSync />
        </Suspense>
        <Preloader />
        <LocaleProvider initialLocale={locale}>
          <Header />
          <PopupBlock />
          <main>
            {children}
          </main>
          <PageUnder footerCategories={footerCategories} />
        </LocaleProvider>
      </body>
    </html>
  );
}
