import ReactLenis from "lenis/react";
import type { Metadata } from "next";
import { DM_Serif_Text, Plus_Jakarta_Sans } from "next/font/google";
import { Suspense } from "react";
import '@splidejs/react-splide/css';
import './global.scss';
import Header from "./_components/general/Header/Header";
import LenisRecovery from "./_components/general/LenisRecovery/LenisRecovery";
import LenisRouteSync from "./_components/general/LenisRouteSync/LenisRouteSync";
import PageUnder from "./_components/general/PageUnder/PageUnder";
import PopupBlock from "./_components/general/PopupBlock/PopupBlock";
import Preloader from "./_components/general/Preloader/Preloader";
const dmSans = DM_Serif_Text({
  variable: "--font-title",
  weight: '400'
});

const plusSans = Plus_Jakarta_Sans({
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "HarbStone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${plusSans.className} h-full antialiased`}
    >
      <body className="min-h-full is-preloading">
        <ReactLenis root />
        <LenisRecovery />
        <Suspense fallback={null}>
          <LenisRouteSync />
        </Suspense>
        <Preloader />
        <Header />
        <PopupBlock />
        <main>
          {children}
        </main>
        <PageUnder/>
      </body>
    </html>
  );
}
